"""make ticket.platform non-nullable

Revision ID: 2540639b85a9
Revises: 1a2b3c4d5e6f
Create Date: 2026-06-21 20:15:38.513820

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "2540639b85a9"
down_revision: str | None = "1a2b3c4d5e6f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Data migration: backfill any NULL platform values to 'mock'
    op.execute("UPDATE tickets SET platform = 'mock' WHERE platform IS NULL")
    # Schema change: make platform non-nullable
    op.alter_column("tickets", "platform", existing_type=sa.String(20), nullable=False)

    # Auto-detected changes (pre-existing drift)
    op.drop_index(op.f("ix_shopify_sessions_is_active"), table_name="shopify_sessions")
    op.add_column(
        "tickets", sa.Column("extra_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tickets", "extra_data")
    op.create_index(
        op.f("ix_shopify_sessions_is_active"), "shopify_sessions", ["is_active"], unique=False
    )
    op.alter_column("tickets", "platform", existing_type=sa.String(20), nullable=True)
    # ### end Alembic commands ###
